env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': off
      max-lines-per-function: off
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
rules:
  '@typescript-eslint/restrict-template-expressions': off
  # TODO(rustyb)[2021-10-30]: Issue upstream in typescript-eslint stopping this rule from working
  # and not in release yet (https://github.com/typescript-eslint/typescript-eslint/pull/3947)
  '@typescript-eslint/no-restricted-imports': ['error', {}]
