name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Continuous Integration'

jobs:
  merge-me:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
    timeout-minutes: 5
